train_mode: refine
loss_type: ll
sn_loss_type: BPR
learner: sgd
learning_rate: 1e-5
l2_norm: 0
weight_decay: 0
max_epochs: 100
eval_step: 1
clip_grad_norm: {'max_norm': 5, 'norm_type': 2}
train_batch_size: 1024
eval_batch_size: 1024
device: 'cuda'
checkpoint_dir: saved_models/ind
eval_mode: all
atten_study: False
list_len: 50
topks: [1,5,10]
num_trials: 2
continue_metric: MRR
eval_metric_bigger: True
seed: 1111
reproducibility: False
lamda1: 0.8
lamda2: 0.1
lamda3: 0.1

margin: 0.2
tau: 0.8

tags_num: 1
have_es: False
batch_neg_size: 5


user_f_pos: [0]
item_f_pos: [1]
sn_f_pos: [2]

have_hist: True

hist_test_dict: data/hvideo/input_data/test_hist_dict_w_hist_len_20.pkl

# train_set_with_two_snid_and_hist_labels.pkl
train_set: data/hvideo/input_data/train_set_all_w_hist_len_20.pkl
test_set: data/hvideo/input_data/test_set_w_hist_len_20.pkl

# saved_models/ind/modem-hvideo-Apr-17-2024_17-55-12.pth map mrr
# saved_models/ind/modem-hvideo-Apr-19-2024_15-35-31.pth ndcg
# saved_models/ind/modem-hvideo-Apr-22-2024_17-39-30.pth
# saved_models/ind/modem-hvideo-Apr-24-2024_14-37-24.pth
# 'saved_models/ind/modem-hvideo-Apr-29-2024_19-44-39.pth' LL
ckpt_file: 'saved_models/ind/modem-hvideo-May-05-2024_18-28-01.pth'



gauc: True
user_is_single_dict: data/hvideo/input_data/user_is_single_dict.pkl

