train_mode: refine
loss_type: ll
sn_loss_type: BPR
learner: adam
learning_rate: 1e-4
l2_norm: 0
weight_decay: 1e-4
max_epochs: 200
eval_step: 5
clip_grad_norm: {'max_norm': 5, 'norm_type': 2}
train_batch_size: 1024
eval_batch_size: 1024
device: 'cuda:0'
checkpoint_dir: saved_models/ind
eval_mode: all
atten_study: False
list_len: 40
topks: [1,5,10]
num_trials: 2  
continue_metric: AUC
eval_metric_bigger: True
seed: 1111
reproducibility: False
lamda1: 1
lamda2: 0
lamda3: 0

margin: 0.2
tau: 0.8

tags_num: 1
have_es: False
batch_neg_size: 5


user_f_pos: [0,1,2,3]
item_f_pos: [4,5]
sn_f_pos: [6]

have_hist: True

hist_test_dict: data/lastfm/input_data/test_hist_dict.pkl

train_set: data/lastfm/input_data/train_set_all.pkl

test_set: data/lastfm/input_data/test_set_small_2000.pkl


ckpt_file: 'saved_models/ind/modem2-lastfm-Apr-23-2024_19-32-43.pth'

gauc: True

user_is_single_dict: data/lastfm/input_data/user_is_single_dict.pkl

